name: Coleta diária de dados da Bahia

on:
  schedule:
    - cron: '0 8 * * *'  # 08:00 UTC todos os dias
  workflow_dispatch:     # Permite rodar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar script de coleta
        run: |
          python baixar_dados_ba_por_data.py

      - name: Subir dados coletados
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git pull
          git add dados/
          git commit -m "📦 Atualização diária dos dados - ${{ github.run_id }}"
          git push