name: Baixar dados do MonitorAr

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia às 12h UTC (9h da manhã no Brasil)
  workflow_dispatch:      # Permite execução manual pelo GitHub

jobs:
  download_data:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install requests pandas

    - name: Executar script de download
      run: python baixar_monitorar.py

    - name: Commit e push se houver mudanças
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Atualização automática dos dados MonitorAr $(date +'%Y-%m-%d %H:%M:%S')" || echo "Sem alterações para commitar"
        git push
